import Chat from '@/compononet/chat';
import GroupList from '@/compononet/groupmodal';
import List from '@/compononet/list';
import UserList from '@/compononet/userlist';
import Protected from '@/hooks/protected';
import API from '@/utils/apiConfig';
import Head from 'next/head'



// pages/index.js
import React, { useEffect, useState } from 'react';


const Home = () => {
  const [currentChatList, setcurrentChatList] = useState([])
  const [selectedUser, setSelectedUser] = useState("ram");
  const [isUserListClick, setisUserListClick] = useState(false)
  const [isGroupListClick, setisgroupListClick] = useState(false)
  const [messageData, setmessageData] = useState([])


  
  const handleUserSelect = (user) => {
    setSelectedUser(user);
    setmessageData([]); // Clear messages when a new user is selected
  };
  const fecthcurrentchat=async()=>{
    try {
      const token=await localStorage.getItem("Token")
      const user=await localStorage.getItem("User")
      const config = {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      };
      API.get("chat",config).then((res)=>{
        const getAllchat=res.data.map((item)=>{
          const senderName=()=>{
            return item?.users[0]?._id==JSON.parse(user)?._id ? item.users[1] :item.users[0]
          }          
          return{
            id:item._id,
            latestmessages:item?.latestMessage?.content ? item?.latestMessage?.content: "click to start new conversations !",
            senderName:item?.isGroupChat ? item?.chatName: senderName()?.name,
            isNewMessage: item?.latestMessage?.sender?._id == JSON.parse(user)?._id ?false :true,
            isGroupChat:item.isGroupChat
          }
        })
        setcurrentChatList([...getAllchat])
        console.log(getAllchat)
      }).catch((err)=>console.log(err))

      
    } catch (error) {
      console.log(error)
      
    }
  }

  const handleSendMessage = () => {
    // Implement sending a message and updating the state here
  };

  useEffect(() => {
    fecthcurrentchat()

    
  
   
  }, [])
  const createNewChat=async(id)=>{
   try {
   
    const token=await localStorage.getItem("Token")
    const config = {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      };
    await API.post("chat",{
      userId:id
    },config).then((res)=>

    {
      const senderName=()=>{
        return res.data?.users[0]?._id==id ? res.data.users[0] :res.data.users[1]
      }          
      const newMessageInstance={
        id:res.data._id,
        latestmessages: "click to start new conversations !",
        senderName: senderName()?.name,
        isNewMessage: false,
        isGroupChat:res.data.isGroupChat
      }
      setcurrentChatList([newMessageInstance,...currentChatList])


    }).catch((err)=>console.log(err))
    
   } catch (error) {
    
   }

  }
  console.log(currentChatList)

  const handleGroupCreate=async(data)=>{
    setisgroupListClick(false)
    const token=await localStorage.getItem("Token")
    const config = {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      };
    await API.post("/chat/group",data,config).then((res)=>{
      const newMessageInstance={
        id:res.data._id,
        latestmessages: "click to start new conversations !",
        senderName: res.data.chatName,
        isNewMessage: false,
        isGroupChat:res.data.isGroupChat
      }
      setcurrentChatList([newMessageInstance,...currentChatList])
    
    }).catch((err)=>{})



  }
  

  return (
    <>
    <Head>
        <title>Contacts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Protected>
      <List isOpen={isUserListClick} setIsOpen={setisUserListClick} onPress={createNewChat} />
      <GroupList isOpen={isGroupListClick} setIsOpen={setisgroupListClick} onPress={handleGroupCreate} />
       <button onClick={()=>setisUserListClick(true)} style={{cursor:'pointer'}}> New Chat </button>
    <div style={{
      display:'flex',
      flexDirection:'row'
    }}>
      <UserList users={currentChatList} selectedUser={selectedUser} setisgroupListClick={setisgroupListClick} onUserSelect={handleUserSelect} />
      <Chat selectedUser={selectedUser} messageData={messageData} setmessageData={setmessageData}  />
    </div>
    </Protected>
    </>
  );
};

export default Home;
