import Head from 'next/head'
import Dashboard from '@/compononet/Screen/dashboard'
export default function Home() {
  return (
    <>
      <Head>
        <title>Contacts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
       
    <Dashboard />
    
        

       
      </main>
    </>
  )
}
