import Layout from '@/compononet/layout'
import Login from '@/compononet/login'
import SignUp from '@/compononet/signup'
import Head from 'next/head'
export default function Home() {
  return (
    <>
      <Head>
        <title>Contacts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
      
        <SignUp />

      </main>
    </>
  )}
